config/routes.rb
Rails.application.routes.draw do
  root 'explorers#index'
  get '/.well-known/acme-challenge/:id' => 'explorers#letsencrypt'
  mount Resque::Server, at: '/resque'
  devise_for :users, path_names: {
    verify_authy: "/verify-token",
    enable_authy: "/enable-two-factor",
    verify_authy_installation: "/verify-installation"
  }
  resources :users, except: [:index] do
    get 'confirm_node_created' => 'chains#confirm_node_created', path: 'chains/confirm_node_created'
    resources :chains do
      get 'start'
      get 'stop'
      
      get 'get_best_block_hash'
      get 'get_block'
      get 'get_blockchain_info'
      get 'get_block_count'
      get 'get_block_hash'
      get 'get_block_header'
      get 'get_chain_tips'
      get 'get_difficulty'
      get 'get_info'
      get 'get_mem_pool_info'
      get 'get_raw_mem_pool'
      get 'get_tx_out'
      get 'get_tx_out_proof'
      get 'get_tx_outset_info'
      get 'verify_chain'
      get 'verify_tx_out_proof'
      
      get 'generate'
      get 'get_generate'
      get 'set_generate'
      
      get 'get_block_template'
      get 'get_mining_info'
      get 'get_network_hashps'
      get 'prioritise_transaction'
      get 'submit_block'
      
      get 'add_node'
      get 'disconnect_node'
      get 'get_added_node_info'
      get 'get_connection_count'
      get 'get_net_totals'
      get 'get_network_info'
      get 'get_peer_info'
      get 'list_banned'
      get 'clear_banned'
      get 'ping'
      get 'set_ban'
      
      get 'create_raw_transaction'
      get 'decode_raw_transaction'
      get 'decode_script'
      get 'get_raw_transaction'
      get 'send_raw_transaction'
      get 'sign_raw_transaction'

      get 'create_multi_sig'
      get 'estimate_fee'
      get 'estimate_priority'
      get 'estimate_smart_fee'
      get 'estimate_smart_priority'
      get 'validate_address'
      get 'verify_message'
    end
  end
  get 'apps/bookmarks' => 'apps#bookmarks'
  get 'apps/calculator' => 'apps#calculator'
  get 'charts/show' => 'charts#show', path: 'charts'
  get 'charts/circulation' => 'charts#circulation'
  get 'charts/market_cap' => 'charts#market_cap'
  get 'charts/transaction_fees_btc' => 'charts#transaction_fees_btc'
  get 'charts/transaction_fees_usd' => 'charts#transaction_fees_usd'
  get 'charts/network_deficit' => 'charts#network_deficit'
  get 'charts/transactions_daily' => 'charts#transactions_daily'
  get 'charts/transactions_total' => 'charts#transactions_total'
  get 'charts/unique_addresses' => 'charts#unique_addresses'
  get 'charts/average_transactions' => 'charts#average_transactions'
  get 'charts/orphaned_blocks' => 'charts#orphaned_blocks'
  get 'charts/total_output_volume' => 'charts#total_output_volume'
  get 'charts/market_price' => 'charts#market_price'
  get 'charts/hash_rate' => 'charts#hash_rate'
  get 'charts/difficulty' => 'charts#difficulty'
  get 'charts/days_destroyed_cumulative' => 'charts#days_destroyed_cumulative'
  get 'charts/days_destroyed' => 'charts#days_destroyed'
  get 'charts/blockchain_size' => 'charts#blockchain_size'
  resources :explorers, only: [:index], path: 'coin'
  get 'explorers/search', path: 'search'
  get 'explorers/cloud', path: 'cloud'
  resources :blocks, only: [:show]
  get 'blocks/transactions/:id' => 'blocks#transactions'
  get 'blocks/raw/:id' => 'blocks#raw'
  resources :transactions, only: [:show]
  get 'transactions/raw/:id' => 'transactions#raw'
  resources :addresses, only: [:show]
  get 'addresses/balance/:id' => 'addresses#balance'
  get 'addresses/unspent/:id' => 'addresses#unspent'
  
  get 'docs/docs'
  get 'docs/developers'
  get 'docs/api'
  get 'docs/security'
  get 'docs/credit'

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  # GET /docs/docs
  def docs
  end

  # GET /docs/developers
  def developers
    client = Octokit::Client.new access_token: Figaro.env.github_token

    #releases = client.releases 'bigearth/blockchain.bigearth.io'
    repos = client.repositories 'bigearth'
    @count = 0
    repos.each do |repo|
      @count += repo.forks_count
      @count += repo.watchers_count
      @count += repo.stargazers_count
    end
    @blockchain_bigearth_io = client.repo 'bigearth/blockchain.bigearth.io'
    @blockchain_bigearth_io_version = client.tags 'bigearth/blockchain.bigearth.io'
    
    @chef_workstation_proxy = client.repo('bigearth/chef_workstation_proxy')
    @chef_workstation_proxy_version = client.tags 'bigearth/chef_workstation_proxy'
    
    @blockchain_proxy = client.repo('bigearth/blockchain_proxy')
    @blockchain_proxy_version = client.tags 'bigearth/blockchain_proxy'
  end

  # GET /docs/api 
  def api
  end

  # GET /docs/security
  def security
  end

  # GET /docs/credit
  def credit
  end
end

app/views/docs/_nav.html.erb
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <!-- <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div> -->
  <div class="sidebar-module">
    <h4>Docs</h4>
    <ol class="list-unstyled">
      <li><%= link_to 'Developers', docs_developers_path %></li>
      <li><%= link_to 'API', docs_api_path %></li>
      <li><%= link_to 'Security', docs_security_path %></li>
      <li><%= link_to 'Credit', docs_credit_path %></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->

app/views/docs/api.html.erb
<div id='docs'>
  <div class='container'>
    <div class="blog-header">
      <h1 class="blog-title">Big Earth Blockchain API</h1>
      <p class="lead blog-description">The official documentation of the Big Earth Blockchain API.</p>
      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
            <p>Here you'll find everything you need to get started w/ the Big Earth Blockchain API.</p>
            <p>All api responses are formatted by the JSend standard. See <%= link_to 'JSend', 'http://labs.omniti.com/labs/jsend' %>.</p>
            
            <h2 id='coin' class="blog-post-title">Coin</h2>
            <p class="blog-post-meta">Coin Info</p>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{explorers_url}.json", "#{explorers_path}.json" %></code>
              </div>
            </div>
            <p> This api presents coin information:</p>
            <ul>
              <li><strong>coin</strong> - Basic coin information with coin name, abbreviation, logo and homepage URL.</li>
              <li><strong>volume</strong> - Volume information: how many coins are in supply and how many coins will there ever be.</li>
              <li><strong>last_block</strong> - Information about the last block in the longest chain.</li>
              <li><strong>next_difficulty</strong> - When will next difficulty be retargeted and how big it will probably be.</li>
              <li><strong>market</strong> - Current price value on markets.</li>
            </ul>
            
            <h2 id='block' class="blog-post-title">Block</h2>
            <p class="blog-post-meta">Block Info</p>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{block_url(200000)}.json", "#{block_path(200000)}.json" %></code>
              </div>
            </div>
            <p>Where <code>200000</code> can be:</p>
            <ul>
              <li><strong>block number</strong> (eg: <code>507</code>)</li>
              <li><strong>block hash</strong> (eg: <code>000000000000000001ccbef03399f9a5a4d7338a471f91d343e52993ef11a0fa</code>)</li>
              <li><strong>word &ldquo;last&rdquo;</strong> this will always return the latest block</li>
              <li><strong>word &ldquo;first&rdquo;</strong> this will always return the first block</li>
            </ul>
            <h3 id='block_txs' class="blog-post-title">Block Transactions</h3>
            <p>Returns short info about all transactions in given block.</p>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{root_url}blocks/transactions/200000.json", "#{root_url}blocks/transactions/200000.json" %></code>
              </div>
            </div>
            <h3 id='block_raw'>Raw Block Data</h3>
            <p>Returns raw block data in the bitcoin format.</p>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{root_url}blocks/raw/200000.json", "#{root_url}blocks/raw/200000.json" %></code>
              </div>
            </div>
            
            <h2 id='adress' class="blog-post-title">Address</h2>
            <p class="blog-post-meta">Address Info</p>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{address_url('1DrK44np3gMKuvcGeFVv9Jk67zodP52eMu')}.json", "#{address_path('1DrK44np3gMKuvcGeFVv9Jk67zodP52eMu')}.json" %></code>
              </div>
            </div>
            <p>Returns basic address data, date, block and transaction, when this address first appeared and last transaction data.</p>
            <p>Address amount is split into two fields:</p>
            <ul>
              <li><strong>amount:</strong> amount of coins linked to this address</li>
              <li><strong>amount_multisig:</strong> amount of coins that this address has in multisignature transactions</li>
            </ul>
            <p>We have them separated because coins in the multisignature transaction do not belong to only one specific address, but to all addresses that are part of this multisignature transaction. It would be wrong to just add that amount to address's amount.</p>
            <h3 id='address_balance'>Address Balance</h3>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{root_url}addresses/balance/1DrK44np3gMKuvcGeFVv9Jk67zodP52eMu.json", "#{root_url}addresses/balance/1DrK44np3gMKuvcGeFVv9Jk67zodP52eMu.json" %></code>
              </div>
            </div>
            <h3 id='address_transactions'>Unspent Transactions</h3>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{root_url}addresses/unspent/1DrK44np3gMKuvcGeFVv9Jk67zodP52eMu.json", "#{root_url}addresses/unspent/1DrK44np3gMKuvcGeFVv9Jk67zodP52eMu.json" %></code>
              </div>
            </div>
            <p>Returns unspent transactions for a given address. Unspent transactions are transactions that still have value. Value of these transactions hasn't been spent yet. Be carefull when using outputs with low number of confirmations (if transaction has more then 6 confirmations then it's usually safe to include it).</p> 
            
            <h2 id='transaction' class="blog-post-title">Transaction</h2>
            <p class="blog-post-meta">Transaction Info</p>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{transaction_url('5752c2cce3c69a0f89f2d21327661819da74ead293cf456c6ca1faeacb449a42')}.json", "#{transaction_path('5752c2cce3c69a0f89f2d21327661819da74ead293cf456c6ca1faeacb449a42')}.json" %></code>
              </div>
            </div>
            <p>Returns transaction data. Some fields are normalized&mdash;<code>vin</code> is presented as an address and not as a previous transaction hash. <code>vins</code> and <code>vouts</code> present actual traded value, not whole transaction amounts. If you need exact transaction presentation, use raw api call.</p>
            <p>This API call returns transaction data for unconfirmed and normal blockchain transactions. It also returns the extra parameter for the unspent vouts. The subkeys for this paramters are:</p>
            <ul>
              <li>vout type (eg: <code>pubkeyhash</code>)</li>
              <li>vout script hash</li>
              <li>vout asm script</li>
              <li>number of signatures required (used for multisig vouts)</li>
            </ul>
            <p>This fields can also be accessed through the raw transaction API call.</p>
            <h3 id='tx_raw'>Raw Transaction Data</h3>
            <p>Returns raw transaction data in the bitcoin format.</p>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Usage</h3>
              </div>
              <div class="panel-body">
                <code><%= link_to "#{root_url}transactions/raw/5752c2cce3c69a0f89f2d21327661819da74ead293cf456c6ca1faeacb449a42.json", "#{root_url}transactions/raw/5752c2cce3c69a0f89f2d21327661819da74ead293cf456c6ca1faeacb449a42.json" %></code>
              </div>
            </div>
            
          </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->
        <%= render 'nav' %>
      </div><!-- /.row -->  
    </div>
  </div>
</div>

app/views/docs/credit.html.erb
<div id='docs'>
  <div class='container'>
    <div class="blog-header">
      <h1 class="blog-title">Big Earth Blockchain Credit</h1>
      <p class="lead blog-description">Giving props to those who helped us get where we are</p>
      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
            <p>It's a web of services and we admit that this site is a mashup of original work along w/ API calls to the Giants that have come before us.</p>
            <p>If you see something that looks familiar it's likely that we're pulling it from the API of one of the following great services. We're incredibly grateful and we wish them the best.</p>
            <ul>
              <li><%= link_to 'Coinbase', 'https://coinbase.com' %></li>
              <li><%= link_to 'Blockchain.info', 'https://blockchain.info' %></li>
              <li><%= link_to 'Blockr', 'https://blockr.io' %></li>
            </ul>
          </div>
        </div><!-- /.blog-main -->
        <%= render 'nav' %>
      </div><!-- /.row -->  
    </div>
  </div>
</div>

app/views/docs/docs.html.erb
<div id='docs'>
  <div class='container'>
    <div class="blog-header">
      <h1 class="blog-title">Big Earth Blockchain Docs</h1>
      <p class="lead blog-description">The official documentation of the Big Earth Blockchain Platform.</p>
      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
            <p>Here you'll find everything you need to get started on the Big Earth Blockchain Platform.</p>
            <ul>
              <li><%= link_to 'Developers', docs_developers_path %></li>
              <li><%= link_to 'API', docs_api_path %></li>
              <li><%= link_to 'Security', docs_security_path %></li>
              <li><%= link_to 'Credit', docs_credit_path %></li>
            </ul>
            <p>Don't see something here and thing it needs to be added? These docs are <%= link_to 'Open Source', 'https://github.com/bigearth/blockchain.bigearth.io/tree/master/app/views/docs' %>. Please fork them, add whatever you think is missing and send us a pull request.</p>
            <p>Have an urgent matter that you need to get in touch w/ us about? Email us at one of the addresses below.</p>
            <ul>
              <li><strong>security@bigearth.io</strong> for any security related questions/comments.</li>
              <li><strong>support@bigearth.io</strong> for any general support related questions/comments.</li>
            </ul>
          </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->
        <%= render 'nav' %>
      </div><!-- /.row -->  
    </div>
  </div>
</div>

app/views/docs/security.html.erb
<div id='docs'>
  <div class='container'>
    <div class="blog-header">
      <h1 class="blog-title">Big Earth Blockchain Security</h1>
      <p class="lead blog-description">Keeping the Big Earth Blockchain Platform safe</p>
      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
            <p>Security is one of the biggest considerations in everything we do. If you have any questions after reading this, or encounter any issues, please contact us at <strong>security@bigearth.io</strong>.</p>
            
            <h2 id='ssl' class="blog-post-title">SSL/TLS &amp; CSRF</h2>
            <p class="blog-post-meta">Encryption between client and server</p>
            <p>HTTPS is enforced for every connection to our website using 2048-bit digital signatures and 128-bit encryption. We also use HTTP Strict Transport Security to ensure requests never interact with our servers over insecure HTTP. Our servers are also protected against CSRF (Cross Site Request Forgery) and Session Fixation.</p>
            
            <h2 id='server_side' class="blog-post-title">Server side best practices</h2>
            <p class="blog-post-meta">Encryption for private user data</p>
            <p>All secrets, credentials and API keys are stored as environment variables and never hardcoded. All passwords are hashed with the bcrypt algorithm including both a pepper and a salt to battle rainbow tables.</p>
            <p>We confirm new profiles via email and also lock profiles down after a specified number of failed sign in attempts. Any time a blockchain is created or destroyed we send out an email to keep you up to date on any changes to your account.</p>
            
            <h2 id='brakeman' class="blog-post-title">Brakeman</h2>
            <p class="blog-post-meta">Static analysis security vulnerability scanner for Rails</p>
            <p>We pass <%= link_to 'Brakeman', 'http://brakemanscanner.org/docs/' %> w/ <strong>0 errors</strong> and <strong>0 security warnings</strong>. Brakeman tests for the following:</p>
            <p>
              <code>
                BasicAuth, BasicAuthTimingAttack, ContentTag, CreateWith, CrossSiteScripting, DefaultRoutes, Deserialize, DetailedExceptions, DigestDoS, DynamicFinders, EscapeFunction, Evaluation, Execute, FileAccess, FileDisclosure, FilterSkipping, ForgerySetting, HeaderDoS, I18nXSS, JRubyXML, JSONEncoding, JSONParsing, LinkTo, LinkToHref, MailTo, MassAssignment, MimeTypeDoS, ModelAttrAccessible, ModelAttributes, ModelSerialize, NestedAttributes, NestedAttributesBypass, NumberToCurrency, QuoteTableName, Redirect, RegexDoS, Render, RenderDoS, RenderInline, ResponseSplitting, RouteDoS, SQL, SQLCVEs, SSLVerify, SafeBufferManipulation, SanitizeMethods, SelectTag, SelectVulnerability, Send, SendFile, SessionManipulation, SessionSettings, SimpleFormat, SingleQuotes, SkipBeforeFilter, StripTags, SymbolDoSCVE, TranslateBug, UnsafeReflection, ValidationRegex, WithoutProtection, XMLDoS, YAMLParsing
              </code>
            </p>
            
            <h2 id='2fa' class="blog-post-title">Two Factor Authentication</h2>
            <p class="blog-post-meta">Something you know and something you have</p>
            <p>We enable Two Factor Authentication via <%= link_to 'Authy', 'https://www.authy.com/' %>. This enables you to add an extra layer of security to your account by requiring a PIN be sent to your phone, either via text or an app, which is used in combination w/ your password to sign in to your profile. This means that even if a bad guy gets your password they're still unable to sign in to your profile w/out your phone as well.</p>
            
            <h2 id='ubuntu' class="blog-post-title">Ubuntu</h2>
            <p class="blog-post-meta">A single non root user over ssh</p>
            <p>First we create a sudoer user. We then whitelist only that username in `sshd_config` and turn off the ability to sign in w/ a password and the ability to sign in as root. This means that *only* our single user can sign in to any of the machines in Big Earth's cloud and *only* over ssh.</p>
            
            <h2 id='chef' class="blog-post-title">Chef</h2>
            <p class="blog-post-meta">Configuration Management &amp; Devops</p>
            <p>Chef gives us the peace of mind that we can spin up an entire cloud w/ each machine being a mirror image of the rest. RSA public key-pairs are used to authenticate a Chef client w/ a Chef server every time the client attempts to access the server.</p>
            
            <h2 id='rails' class="blog-post-title">Rails Security</h2>
            <p class="blog-post-meta">Our foundation</p>
            <p>Ruby on Rails rolls best practices into the framework which leads developers to do the right thing out of the box. On top of that they have an active security team which keeps the framework up to date and secure as new issues arise. You can read about Rails security best practices.</p>
            <ul>
              <li><%= link_to 'Rails Security', 'http://guides.rubyonrails.org/security.html' %></li>
            </ul>
            
            <h2 id='heroku' class="blog-post-title">Heroku &amp; Digital Ocean Security</h2>
            <p class="blog-post-meta">Platorms which we build on</p>
            <p>Big Earth Blockchain servers are hosted on Heroku and Digital Ocean. You can read about their security measures in place to protect our infrastructure.</p>
            <ul>
              <li><%= link_to 'Heroku Security', 'https://www.heroku.com/policy/security' %></li>
              <li><%= link_to 'Digital Ocean Security', 'https://www.digitalocean.com/security' %></li>
            </ul>
            
            <h2 id='cloudflare' class="blog-post-title">CloudFlare &amp; DNSSEC</h2>
            <p class="blog-post-meta">Worldwide CDN and Firewall</p>
            <p>Cloudflare handles our nameservers and DNS which enables us to be protected against the largest DDoS attacks on the Web. We also use them to compress our content and cache it on their edge servers to drastically improve site performance. We use CloudFlare to enable DNSSEC to authenticate DNS records. 
              
            <h2 id='network_diagram' class="blog-post-title">Network Diagram</h2>
            <p class="blog-post-meta">The lay of the land</p>
            <p><%= image_tag asset_path('network_topography.png'), class: 'network_topography' %></p>
            
            <h2 id='open_source' class="blog-post-title">Open Source</h2>
            <p class="blog-post-meta">Peer Review</p>
            <p>Our entire infrastructure is open source. We highly suggest you clone the repo and dig around to see how things work. Make some improvements and send us a pull-request. We'd be thrilled!</p>
            <p>Find out more by checking out our <%= link_to 'Developers page', docs_developers_path %>.</p>
            
            <h2 id='contact' class="blog-post-title">Something missing? Contact Us</h2>
            <p class="blog-post-meta">Help us improve</p>
            <p>If you’ve found a vulnerability in our service or website, or want additional information regarding how we manage security, please send an email to <strong>security@bigearth.io</strong>. We'll review it and respond to you within 24 hours.</p>
            <p>Have an urgent matter that you need to get in touch w/ us about? Email us at <strong>support@bigearth.io</strong> for any general support related questions/comments.</p>
            <p>Don't see something here and think it needs to be added? These docs are <%= link_to 'Open Source', 'https://github.com/bigearth/blockchain.bigearth.io/tree/master/app/views/docs' %>. Please fork them, add whatever you think is missing and send us a pull request.</p>
            
          </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->
        <%= render 'nav' %>
      </div><!-- /.row --> 
    </div>
  </div>
</div>