config/routes.rb
Rails.application.routes.draw do
  root 'explorers#index'
  get '/.well-known/acme-challenge/:id' => 'explorers#letsencrypt'
  mount Resque::Server, at: '/resque'
  devise_for :users, path_names: {
    verify_authy: "/verify-token",
    enable_authy: "/enable-two-factor",
    verify_authy_installation: "/verify-installation"
  }
  resources :users, except: [:index] do
    get 'confirm_node_created' => 'chains#confirm_node_created', path: 'chains/confirm_node_created'
    resources :chains do
      get 'start'
      get 'stop'
      
      get 'get_best_block_hash'
      get 'get_block'
      get 'get_blockchain_info'
      get 'get_block_count'
      get 'get_block_hash'
      get 'get_block_header'
      get 'get_chain_tips'
      get 'get_difficulty'
      get 'get_info'
      get 'get_mem_pool_info'
      get 'get_raw_mem_pool'
      get 'get_tx_out'
      get 'get_tx_out_proof'
      get 'get_tx_outset_info'
      get 'verify_chain'
      get 'verify_tx_out_proof'
      
      get 'generate'
      get 'get_generate'
      get 'set_generate'
      
      get 'get_block_template'
      get 'get_mining_info'
      get 'get_network_hashps'
      get 'prioritise_transaction'
      get 'submit_block'
      
      get 'add_node'
      get 'disconnect_node'
      get 'get_added_node_info'
      get 'get_connection_count'
      get 'get_net_totals'
      get 'get_network_info'
      get 'get_peer_info'
      get 'list_banned'
      get 'clear_banned'
      get 'ping'
      get 'set_ban'
      
      get 'create_raw_transaction'
      get 'decode_raw_transaction'
      get 'decode_script'
      get 'get_raw_transaction'
      get 'send_raw_transaction'
      get 'sign_raw_transaction'

      get 'create_multi_sig'
      get 'estimate_fee'
      get 'estimate_priority'
      get 'estimate_smart_fee'
      get 'estimate_smart_priority'
      get 'validate_address'
      get 'verify_message'
    end
  end
  get 'apps/bookmarks' => 'apps#bookmarks'
  get 'apps/calculator' => 'apps#calculator'
  get 'charts/show' => 'charts#show', path: 'charts'
  get 'charts/circulation' => 'charts#circulation'
  get 'charts/market_cap' => 'charts#market_cap'
  get 'charts/transaction_fees_btc' => 'charts#transaction_fees_btc'
  get 'charts/transaction_fees_usd' => 'charts#transaction_fees_usd'
  get 'charts/network_deficit' => 'charts#network_deficit'
  get 'charts/transactions_daily' => 'charts#transactions_daily'
  get 'charts/transactions_total' => 'charts#transactions_total'
  get 'charts/unique_addresses' => 'charts#unique_addresses'
  get 'charts/average_transactions' => 'charts#average_transactions'
  get 'charts/orphaned_blocks' => 'charts#orphaned_blocks'
  get 'charts/total_output_volume' => 'charts#total_output_volume'
  get 'charts/market_price' => 'charts#market_price'
  get 'charts/hash_rate' => 'charts#hash_rate'
  get 'charts/difficulty' => 'charts#difficulty'
  get 'charts/days_destroyed_cumulative' => 'charts#days_destroyed_cumulative'
  get 'charts/days_destroyed' => 'charts#days_destroyed'
  get 'charts/blockchain_size' => 'charts#blockchain_size'
  resources :explorers, only: [:index], path: 'coin'
  get 'explorers/search', path: 'search'
  get 'explorers/cloud', path: 'cloud'
  resources :blocks, only: [:show]
  get 'blocks/transactions/:id' => 'blocks#transactions'
  get 'blocks/raw/:id' => 'blocks#raw'
  resources :transactions, only: [:show]
  get 'transactions/raw/:id' => 'transactions#raw'
  resources :addresses, only: [:show]
  get 'addresses/balance/:id' => 'addresses#balance'
  get 'addresses/unspent/:id' => 'addresses#unspent'
  
  get 'docs/docs'
  get 'docs/developers'
  get 'docs/api'
  get 'docs/security'
  get 'docs/credit'

end

app/views/shared/_breadcrumb.html.erb
<ul class='breadcrumb'>
<li><%= link_to 'Home', root_url %></li>
<% if params[:action] == 'cloud' %>
  <li class='active'>Cloud</li>
<% elsif params[:controller] == 'blocks' %>
  <li class='active'>Block <%= number_with_delimiter @block['data']['nb'], delimiter: ',' %></li>
<% elsif params[:controller] == 'addresses' %>
  <li class='active'>Address <%= @address['data']['address'] %></li>
<% elsif params[:action] == 'bookmarks' %>
  <li class='active'>Bookmarks</li>
<% elsif params[:action] == 'calculator' %>
  <li class='active'>Calculator</li>
<% elsif params[:controller] == 'chains' %>
  <li class='active'>Blockchains</li>
  <% if params[:action] == 'new' %>
    <li class='active'>New</li>
  <% elsif params[:action] == 'edit' %>
    <li class='active'>Edit</li>
  <% elsif params[:action] == 'show' %>
    <li class='active'><%= @chain.title %></li>
  <% end %>
<% elsif params[:controller] == 'users' %>
    <li class='active'>Profile</li>
  <% if params[:action] == 'show' %>
    <li class='active'><%= current_user.email %></li>
  <% elsif params[:action] == 'edit' %>
    <li class='active'>Edit</li>
  <% end %>
<% elsif params[:controller] == 'devise/registrations' %>
  <li class='active'>Profile</li>
  <li class='active'>Sign Up</li>
<% elsif params[:controller] == 'devise/sessions' %>
  <li class='active'>Profile</li>
  <li class='active'>Sign In</li>
<% elsif params[:controller] == 'devise/devise_authy' %>
  <li class='active'>2FA</li>
  <% if params[:action] == 'GET_enable_authy' %>
    <li class='active'>Enable</li>
  <% else %>
    <li class='active'>Verify</li>
  <% end %>
<% elsif params[:controller] == 'devise_authy/passwords' && params[:action] == 'new' %>
  <li class='active'>Profile</li>
  <li class='active'>Forgot Password</li>
<% elsif params[:controller] == 'devise_authy/passwords' && params[:action] == 'edit' %>
  <li class='active'>Profile</li>
  <li class='active'>New Password</li>
<% elsif params[:controller] == 'devise/confirmations' %>
  <li class='active'>Profile</li>
  <li class='active'>Resend</li>
<% elsif params[:controller] == 'charts' %>
  <% if params[:action] == 'show' %>
    <li class='active'>Charts</li>
  <% else %>
    <li><%= link_to 'Charts', charts_show_path %></li>
  <% end %>
  <% if params[:action] == 'circulation' %>
    <li class='active'>Circulation</li>
  <% elsif params[:action] == 'market_cap' %>
    <li class='active'>Market Capitalization</li>
  <% elsif params[:action] == 'transaction_fees_btc' %>
    <li class='active'>Transaction Fees (BTC)</li>
  <% elsif params[:action] == 'transaction_fees_usd' %>
    <li class='active'>Transaction Fees (USD)</li>
  <% elsif params[:action] == 'network_deficit' %>
    <li class='active'>Network Deficit</li>
  <% elsif params[:action] == 'transactions_daily' %>
    <li class='active'>Total Transactions Daily</li>
  <% elsif params[:action] == 'transactions_total' %>
    <li class='active'>Total Transactions</li>
  <% elsif params[:action] == 'unique_addresses' %>
    <li class='active'>Unique Addresses</li>
  <% elsif params[:action] == 'average_transactions' %>
    <li class='active'>Average Transactions</li>
  <% elsif params[:action] == 'orphaned_blocks' %>
    <li class='active'>Orphaned Blocks</li>
  <% elsif params[:action] == 'total_output_volume' %>
    <li class='active'>Total Output Volume</li>
  <% elsif params[:action] == 'market_price' %>
    <li class='active'>Market Price</li>
  <% elsif params[:action] == 'hash_rate' %>
    <li class='active'>Hash Rate</li>
  <% elsif params[:action] == 'difficulty' %>
    <li class='active'>Difficulty</li>
  <% elsif params[:action] == 'days_destroyed_cumulative' %>
    <li class='active'>Days Destroyed Cumulative</li>
  <% elsif params[:action] == 'days_destroyed' %>
    <li class='active'>Days Destroyed</li>
  <% elsif params[:action] == 'blockchain_size' %>
    <li class='active'>Blockchain Size</li>
  <% end %>
<% elsif params[:controller] == 'docs' %>
    <li class='active'>Docs</li>
  <% if params[:action] == 'developers' %>
    <li class='active'>Developers</li>
  <% end %>
<% end %>
</ul>

app/views/shared/_footer.html.erb
<span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span> <%= Time.now.strftime('%Y') %>
<%= link_to 'gabr13l', "https://twitter.com/cgcardona", class: 'btn btn-sm' %>

app/views/shared/_google_analytics.html.erb
<div id='google_analytics_tracking_id' data-tracking="<%= Figaro.env.google_analytics_tracking_id %>"></div>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', $('#google_analytics_tracking_id').data('tracking'), 'auto');
ga('send', 'pageview');

</script>

app/views/shared/_nav_bar.html.erb
<nav class='navbar navbar-default navbar-static-top'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to 'Big Earth', root_url, class: 'navbar-brand' %>
    </div>
    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
      <ul class='nav navbar-nav'>
        <li class='<%= if (params[:controller] == 'addresses' || params[:controller] == 'blocks' || params[:controller] == 'transactions' || (params[:action] == 'index' && params[:controller] == 'explorers')) then 'active' end %>'>
          <%= link_to root_url do %>
            <span class='text-primary glyphicon glyphicon-th-large'></span>
            Blockchain Explorer
            <span id='bookmark_count_badge' class='hide label label-primary label-as-badge'></span>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class='<%= if (params[:controller] == 'users' || params[:controller] == 'chains') then 'active' end %>'>
            <%= link_to user_path current_user do %>
              <span class='text-primary glyphicon glyphicon-user'></span>
              Profile
            <% end %>
          </li>
        <% else %>
          <li class='<%= if params[:controller] == 'devise/sessions' || params[:controller] == 'devise/registrations' || params[:controller] == 'devise_authy/passwords' || params[:controller] == 'devise/confirmations' then 'active' end %>'>
            <%= link_to new_user_session_path do %>
              <span class='text-primary glyphicon glyphicon-user'></span>
              Sign in
            <% end %>
          </li>
        <% end %>
        <li class='<%= if params[:action] == 'bookmarks' then 'active' end %>'>
          <%= link_to apps_bookmarks_path do %>
            <span class='text-primary glyphicon glyphicon-bookmark'></span>
            Bookmarks
            <span id='bookmark_count_badge' class='hide label label-primary label-as-badge'></span>
          <% end %>
        </li>
        <li class='<%= if params[:action] == 'calculator' then 'active' end %>'>
          <%= link_to apps_calculator_path do %>
            <span class='text-primary glyphicon glyphicon-phone'></span>
            Calculator
          <% end %>
        </li>
        <li class='<%= if params[:controller] == 'charts'  then 'active' end %>'>
          <%= link_to charts_show_path do %>
            <span class='text-primary glyphicon glyphicon-dashboard'></span>
            Charts
          <% end %>
        </li>
        <li class='<%= if params[:controller] == 'docs'  then 'active' end %>'>
          <%= link_to docs_docs_path do %>
            <span class='text-primary glyphicon glyphicon-globe'></span>
            Docs
          <% end %>
        </li>
        <li>
          <%= link_to 'http://blog.bigearth.io' do %>
            <span class='text-primary glyphicon glyphicon-list-alt'></span>
            Blog
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_social_media.html.erb
<% tweet_text = "https://twitter.com/intent/tweet?text=#{create_page_title}Big Earth Blockchain Explorer - #{request.original_url}" %>
<%= link_to URI.escape(tweet_text), class: 'btn btn-lg' do %> 
  <span class="fa fa-twitter"></span> 
<% end %>
<%= link_to "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}", class: 'btn btn-lg' do %>
  <span class="fa fa-facebook"></span> 
<% end %>
<% unless current_page?(root_url) || current_page?(apps_calculator_path) || params[:controller] == 'chains' || params[:controller] == 'charts' || params[:controller] == 'users' || params[:controller] == 'devise/registrations' || params[:controller] == 'devise/sessions' || params[:controller] == 'devise/devise_authy' || params[:controller] == 'devise_authy/passwords' || params[:controller] == 'devise/confirmations' %>
  <% if current_page?(apps_bookmarks_path) %>
    <%= link_to '#', class: 'btn btn-sm clear_all_bookmarks' do %>
      <span class="text-primary glyphicon glyphicon-remove" aria-hidden="true"></span>
      Delete All
    <% end %>
  <% elsif current_page?(apps_bookmarks_path) != '/apps/bookmarks' %>
    <%= link_to '#', id: 'create_bookmark', class: 'btn btn-sm', "data-bookmark_type" => create_bookmark_type, "data-page_id" => params[:id] do %> 
      <span class="text-primary glyphicon glyphicon-bookmark" aria-hidden="true"></span> 
      <span id='create_bookmark_description'>Add to Bookmarks</span>
    <% end %>
  <% end %>
<% end %>
<% if params[:controller] == 'chains' || params[:controller] == 'users' %>
  <%= link_to new_user_chain_path(@user), class: 'btn btn-sm' do %>
    <span class="text-primary glyphicon glyphicon-th-large" aria-hidden="true"></span>
    New Blockchain
  <% end %>
<% end %>