config/routes.rb
Rails.application.routes.draw do
  root 'explorers#index'
  get '/.well-known/acme-challenge/:id' => 'explorers#letsencrypt'
  mount Resque::Server, at: '/resque'
  devise_for :users, path_names: {
    verify_authy: "/verify-token",
    enable_authy: "/enable-two-factor",
    verify_authy_installation: "/verify-installation"
  }
  resources :users, except: [:index] do
    get 'confirm_node_created' => 'chains#confirm_node_created', path: 'chains/confirm_node_created'
    resources :chains do
      get 'start'
      get 'stop'
      
      get 'get_best_block_hash'
      get 'get_block'
      get 'get_blockchain_info'
      get 'get_block_count'
      get 'get_block_hash'
      get 'get_block_header'
      get 'get_chain_tips'
      get 'get_difficulty'
      get 'get_info'
      get 'get_mem_pool_info'
      get 'get_raw_mem_pool'
      get 'get_tx_out'
      get 'get_tx_out_proof'
      get 'get_tx_outset_info'
      get 'verify_chain'
      get 'verify_tx_out_proof'
      
      get 'generate'
      get 'get_generate'
      get 'set_generate'
      
      get 'get_block_template'
      get 'get_mining_info'
      get 'get_network_hashps'
      get 'prioritise_transaction'
      get 'submit_block'
      
      get 'add_node'
      get 'disconnect_node'
      get 'get_added_node_info'
      get 'get_connection_count'
      get 'get_net_totals'
      get 'get_network_info'
      get 'get_peer_info'
      get 'list_banned'
      get 'clear_banned'
      get 'ping'
      get 'set_ban'
      
      get 'create_raw_transaction'
      get 'decode_raw_transaction'
      get 'decode_script'
      get 'get_raw_transaction'
      get 'send_raw_transaction'
      get 'sign_raw_transaction'

      get 'create_multi_sig'
      get 'estimate_fee'
      get 'estimate_priority'
      get 'estimate_smart_fee'
      get 'estimate_smart_priority'
      get 'validate_address'
      get 'verify_message'
    end
  end
  get 'apps/bookmarks' => 'apps#bookmarks'
  get 'apps/calculator' => 'apps#calculator'
  get 'charts/show' => 'charts#show', path: 'charts'
  get 'charts/circulation' => 'charts#circulation'
  get 'charts/market_cap' => 'charts#market_cap'
  get 'charts/transaction_fees_btc' => 'charts#transaction_fees_btc'
  get 'charts/transaction_fees_usd' => 'charts#transaction_fees_usd'
  get 'charts/network_deficit' => 'charts#network_deficit'
  get 'charts/transactions_daily' => 'charts#transactions_daily'
  get 'charts/transactions_total' => 'charts#transactions_total'
  get 'charts/unique_addresses' => 'charts#unique_addresses'
  get 'charts/average_transactions' => 'charts#average_transactions'
  get 'charts/orphaned_blocks' => 'charts#orphaned_blocks'
  get 'charts/total_output_volume' => 'charts#total_output_volume'
  get 'charts/market_price' => 'charts#market_price'
  get 'charts/hash_rate' => 'charts#hash_rate'
  get 'charts/difficulty' => 'charts#difficulty'
  get 'charts/days_destroyed_cumulative' => 'charts#days_destroyed_cumulative'
  get 'charts/days_destroyed' => 'charts#days_destroyed'
  get 'charts/blockchain_size' => 'charts#blockchain_size'
  resources :explorers, only: [:index], path: 'coin'
  get 'explorers/search', path: 'search'
  get 'explorers/cloud', path: 'cloud'
  resources :blocks, only: [:show]
  get 'blocks/transactions/:id' => 'blocks#transactions'
  get 'blocks/raw/:id' => 'blocks#raw'
  resources :transactions, only: [:show]
  get 'transactions/raw/:id' => 'transactions#raw'
  resources :addresses, only: [:show]
  get 'addresses/balance/:id' => 'addresses#balance'
  get 'addresses/unspent/:id' => 'addresses#unspent'
  
  get 'docs/docs'
  get 'docs/developers'
  get 'docs/api'
  get 'docs/security'
  get 'docs/credit'

end

app/models/charts/average_transaction.rb
module Charts
  class AverageTransaction
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/block_size.rb
module Charts
  class BlockSize
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/circulation.rb
module Charts
  class Circulation
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/days_destroyed.rb
module Charts
  class DaysDestroyed
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/days_destroyed_cumulative.rb
module Charts
  class DaysDestroyedCumulative
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/difficulty.rb
module Charts
  class Difficulty
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/hash_rate.rb
module Charts
  class HashRate 
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/market_cap.rb
module Charts
  class MarketCap
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/market_price.rb
module Charts
  class MarketPrice
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/network_deficit.rb
module Charts
  class NetworkDeficit
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/orphaned_block.rb
module Charts
  class OrphanedBlock
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/total_output.rb
module Charts
  class TotalOutput
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/transaction_daily.rb
module Charts
  class TransactionDaily
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/transaction_fee_btc.rb
module Charts
  class TransactionFeeBtc
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/transaction_fee_usd.rb
module Charts
  class TransactionFeeUsd
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/transaction_total.rb
module Charts
  class TransactionTotal
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/models/charts/unique_address.rb
module Charts
  class UniqueAddress
    include Mongoid::Document
    field :time, type: Integer
    field :total, type: BigDecimal
  end  
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  # before_action :set_transaction, only: [:edit, :update, :destroy]

  # GET /charts/show
  # GET /charts/show.json
  def show 
  end

  # GET /charts/circulation
  # GET /charts/circulation.json
  def circulation
    @circulations = Charts::Circulation.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end

  # GET /charts/market_cap
  # GET /charts/market_cap.json
  def market_cap
    @market_cap = Charts::MarketCap.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end

  # GET /charts/transaction_fees_btc
  # GET /charts/transaction_fees_btc.json
  def transaction_fees_btc
    @transaction_fees_btc = Charts::TransactionFeeBtc.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/transaction_fees_usd
  # GET /charts/transaction_fees_usd.json
  def transaction_fees_usd
    @transaction_fees_usd = Charts::TransactionFeeUsd.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/network_deficit
  # GET /charts/network_deficit.json
  def network_deficit
    @network_deficit  = Charts::NetworkDeficit.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/transactions_daily
  # GET /charts/transactions_daily.json
  def transactions_daily
    @transactions_daily = Charts::TransactionDaily.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/transactions_total
  # GET /charts/transactions_total.json
  def transactions_total
    @transactions_total = Charts::TransactionTotal.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/unique_addresses
  # GET /charts/unique_addresses.json
  def unique_addresses
    @unique_addresses = Charts::UniqueAddress.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/average_transactions
  # GET /charts/average_transactions.json
  def average_transactions 
    @average_transactions = Charts::AverageTransaction.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/orphaned_blocks
  # GET /charts/orphaned_blocks.json
  def orphaned_blocks
    @orphaned_blocks = Charts::OrphanedBlock.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/total_output_volume
  # GET /charts/total_output_volume.json
  def total_output_volume
    @total_output_volume = Charts::TotalOutput.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/market_price
  # GET /charts/market_price.json
  def market_price
    @market_price = Charts::MarketPrice.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/hash_rate
  # GET /charts/hash_rate.json
  def hash_rate
    @hash_rate = Charts::HashRate.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/difficulty
  # GET /charts/difficulty.json
  def difficulty
    @difficulty = Charts::Difficulty.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/days_destroyed_cumulative
  # GET /charts/days_destroyed_cumulative.json
  def days_destroyed_cumulative
    @days_destroyed_cumulative = Charts::DaysDestroyedCumulative.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/days_destroyed
  # GET /charts/days_destroyed.json
  def days_destroyed
    @days_destroyed = Charts::DaysDestroyed.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end
  
  # GET /charts/blockchain_size
  # GET /charts/blockchain_size.json
  def blockchain_size
    @blockchain_size = Charts::BlockSize.all.map do |item| 
      [DateTime.strptime(item['time'].to_s,'%s').strftime("%b'%y"), item['total'].to_i]
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_transaction
    #   @transaction = Transaction.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circulation_params
      params[:circulation]
    end
end

app/views/charts/average_transactions.html.erb
<div class='hero'>
  <div class='container'>
    <section class="row m-b-md">
        <div class="col-sm-12">
          <h2><span class='glyphicon glyphicon-dashboard' aria-hidden='true'></span> Bitcoin <strong>Charts</strong></h2>
          <%= render 'shared/breadcrumb' %>
          <%= render 'shared/social_media' %>
        </div>
    </section>
  </div>
</div>
<div class='sub'>
  <section id='data' class='container' data-average_transactions='<%= @average_transactions.to_json %>'>
    <div id='average_transactions_chart'></div>
  </section>
</div>
<script>
window.onload = function() {
  'use strict';  
  google.charts.setOnLoadCallback(draw_average_transactions_chart);

  function draw_average_transactions_chart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Time');
    data.addColumn('number', 'Total');
    data.addRows(JSON.parse(document.getElementById('data').dataset.average_transactions));

    var options = {
      title: 'Average Number of Transactions per Block',
      height: 400,
      colors: ['#0f5288'],
      chartArea: {
        width: '90%',
        height: '80%',
        left: 75,
        right: 25
      },
      hAxis: {
        gridlines: {
          color: 'transparent'
        }
      },
      vAxis: {
        title: 'Transactions per Block',
        format: 'short'
      },
      legend: {
        position: 'none'
      }
    };

    var chart = new google.visualization.LineChart(document.getElementById('average_transactions_chart'));
    resize(function () {
      chart.draw(data, options);
    });
  }
};
</script>

app/views/charts/blockchain_size.html.erb
<div class='hero'>
  <div class='container'>
    <section class="row m-b-md">
        <div class="col-sm-12">
          <h2><span class='glyphicon glyphicon-dashboard' aria-hidden='true'></span> Bitcoin <strong>Charts</strong></h2>
          <%= render 'shared/breadcrumb' %>
          <%= render 'shared/social_media' %>
        </div>
    </section>
  </div>
</div>
<div class='sub'>
  <section id='data' class='container' data-blockchain_size='<%= @blockchain_size.to_json %>'>
    <div id='blockchain_size_chart'></div>
  </section>
</div>
<script>
window.onload = function() {
  'use strict';  
  google.charts.setOnLoadCallback(draw_blockchain_size_chart);

  function draw_blockchain_size_chart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Time');
    data.addColumn('number', 'Total');
    data.addRows(JSON.parse(document.getElementById('data').dataset.blockchain_size));

    var options = {
      title: 'Blockchain Size',
      height: 400,
      colors: ['#0f5288'],
      chartArea: {
        width: '90%',
        height: '80%',
        left: 75,
        right: 25
      },
      hAxis: {
        gridlines: {
          color: 'transparent'
        }
      },
      vAxis: {
        title: 'MB',
        format: 'short'
      },
      legend: {
        position: 'none'
      }
    };

    var chart = new google.visualization.LineChart(document.getElementById('blockchain_size_chart'));
    resize(function () {
      chart.draw(data, options);
    });
  }
};
</script>

app/views/charts/show.html.erb
<div class='hero'>
  <div class='container'>
    <section class="row m-b-md">
        <div class="col-sm-12">
          <h2><span class='glyphicon glyphicon-dashboard' aria-hidden='true'></span> Bitcoin <strong>Charts</strong></h2>
          <%= render 'shared/breadcrumb' %>
          <%= render 'shared/social_media' %>
        </div>
    </section>
  </div>
</div>
<div class='sub' id='charts'>
  <section class='container'>
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'circulation.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='total_circulation'>
          <%= link_to 'Total Bitcoins in Circulation', charts_circulation_path %>
        </h3>
        <p>Bitcoins are created each time a user discovers a new block. The rate of block creation is adjusted every 2016 blocks to aim for a constant two week adjustment period (equivalent to 6 per hour.) The number of bitcoins generated per block is set to decrease geometrically, with a 50% reduction every 210,000 blocks, or approximately four years. The result is that the number of bitcoins in existence is not expected to exceed 21 million.[2] Speculated justifications for the unintuitive value &ldquo;21 million&rdquo; are that it matches a 4-year reward halving schedule; or the ultimate total number of Satoshis that will be mined is close to the maximum capacity of a 64-bit floating point number. Satoshi has never really justified or explained many of these constants.</p>
        <p>
        <%= link_to 'https://en.bitcoin.it/wiki/Controlled_supply#Currency_with_Finite_Supply' do %>
          <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
        <% end %>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'total_transaction_fees.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='transaction_fees_btc'>
          <%= link_to 'Total Transaction Fees (BTC)', charts_transaction_fees_btc_path %>
        </h3>
        <p>Transaction fees may be included with any transfer of bitcoins from one address to another. At the moment, many transactions are typically processed in a way where no fee is expected at all, but for transactions which draw coins from many bitcoin addresses and therefore have a large data size, a small transaction fee is usually expected.</p>
        <p>The transaction fee is processed by and received by the bitcoin miner. When a new bitcoin block is generated with a successful hash, the information for all of the transactions is included with the block and all transaction fees are collected by that user creating the block, who is free to assign those fees to himself.</p>
        <p>Transaction fees are voluntary on the part of the person making the bitcoin transaction, as the person attempting to make a transaction can include any fee or none at all in the transaction. On the other hand, nobody mining new bitcoins necessarily needs to accept the transactions and include them in the new block being created. The transaction fee is therefore an incentive on the part of the bitcoin user to make sure that a particular transaction will get included into the next block which is generated.</p>
        <p>It is envisioned that over time the cumulative effect of collecting transaction fees will allow somebody creating new blocks to "earn" more bitcoins than will be mined from new bitcoins created by the new block itself. This is also an incentive to keep trying to create new blocks even if the value of the newly created block from the mining activity is zero in the far future.</p>
        <p>
          <%= link_to 'https://en.bitcoin.it/wiki/Controlled_supply#Currency_with_Finite_Supply' do %>
            <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
          <% end %>
        </p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'total_transaction_fees_usd.png' %>
      </div>
      <div class="col-sm-8 chart_link">
      </div>
      
      <div class="col-sm-8 chart_link">
        <h3 id='transaction_fees_usd'>
          <%= link_to 'Transaction Fees (USD)', charts_transaction_fees_usd_path %>
        </h3>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'capitalization.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='market_cap'>
          <%= link_to 'Market Capitalization', charts_market_cap_path %>
        </h3>
        <p>The total number of bitcoins in circulation multiplied by the USD market price.</p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'deficit.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='network_deficit'>
          <%= link_to 'Network Deficit', charts_network_deficit_path %>
        </h3>
        <p>The difference between transaction fees and the bitcoin miners income from block rewards. So if a Block has 25 BTC generated and 1 BTC of fees, the network deficit would be 24 BTC. The amount in USDs is calculated at the spot rate at the time.</p>
        <p>
          <%= link_to 'http://bitcoin.stackexchange.com/questions/10230/how-is-network-deficit-calculated#answer-10263' do %>
            <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
          <% end %>
        </p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'transactions_per_day.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='daily_transactions'>
          <%= link_to 'Transactions (daily)', charts_transactions_daily_path %>
        </h3>
        <p>A transaction is a transfer of Bitcoin value that is broadcast to the network and collected into blocks. A transaction typically references previous transaction outputs as new transaction inputs and dedicates all input Bitcoin values to new outputs. Transactions are not encrypted, so it is possible to browse and view every transaction ever collected into a block.</p>
        <p>
          <%= link_to 'https://en.bitcoin.it/wiki/Transaction' do %>
            <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
          <% end %>
        </p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'total_number_of_transactions.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='total_transactions'>
          <%= link_to 'Transactions (total)', charts_transactions_total_path %>
        </h3>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'unique_addresses.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='unique_addresses'>
          <%= link_to 'Unique Addresses', charts_unique_addresses_path %>
        </h3>
        <p>A Bitcoin address, or simply address, is an identifier of 26-35 alphanumeric characters, beginning with the number 1 or 3, that represents a possible destination for a bitcoin payment. Addresses can be generated at no cost by any user of Bitcoin. </p>
        <p>Like e-mail addresses, you can send bitcoins to a person by sending bitcoins to one of their addresses. However, unlike e-mail addresses, people have many different Bitcoin addresses and a unique address should be used for each transaction. Most Bitcoin software and websites will help with this by generating a brand new address each time you create an invoice or payment request.</p>
        <p>
          <%= link_to 'https://en.bitcoin.it/wiki/Address' do %>
            <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
          <% end %>
        </p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'avg_txs_per_block.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='avg_transactions'>
          <%= link_to 'Average Transactions per Block', charts_average_transactions_path %>
        </h3>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'orphaned_blocks.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='orphaned_blocks'>
          <%= link_to 'Orphaned Blocks', charts_orphaned_blocks_path %>
        </h3>
        <p>An orphan block is a block that doesn't have a known parent in the longest block chain.</p>
        <p>
          <%= link_to 'https://en.bitcoin.it/wiki/Orphan_Block' do %>
            <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
          <% end %>
        </p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'output_volume.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='total_output_volume'>
          <%= link_to 'Total Output Volume', charts_total_output_volume_path %>
        </h3>
        <p>Total value of all transaction outputs per day. Including coins returned as change to the sender.</p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'market_price_usd.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='market_price'>
          <%= link_to 'Market Price', charts_market_price_path %>
        </h3>
        <p>The USD market price shown from the major exchanges</p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'hash_rate.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='hash_rate'>
          <%= link_to 'Hash Rate', charts_hash_rate_path %>
        </h3>
        <p>The estimated number of giga hashes per second (billions of hashes per second) the bitcoin network is performing.</p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'difficulty.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='difficulty'>
          <%= link_to 'Difficulty', charts_difficulty_path %>
        </h3>
        <p>Difficulty is a measure of how difficult it is to find a hash below a given target. The Bitcoin network has a global block difficulty. Valid blocks must have a hash below this target. Mining pools also have a pool-specific share difficulty setting a lower limit for shares.</p>
        <p>
          <%= link_to 'https://en.bitcoin.it/wiki/Difficulty' do %>
            <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
          <% end %>
        </p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'days_destroyed_cumulative.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='days_destroyed_cumulative'>
          <%= link_to 'Days Destroyed Cumulative', charts_days_destroyed_cumulative_path %>
        </h3>
        <p>Bitcoin Days Destroyed is a measure of the transaction volume of Bitcoin. Bitcoin days destroyed for any given transaction is calculated by taking the number of Bitcoins in a transaction and multiplying it by the number of days it has been since those coins were last spent.</p>
        <p>
          <%= link_to 'https://en.bitcoin.it/wiki/Bitcoin_Days_Destroyed' do %>
            <span class='glyphicon glyphicon-info-sign' aria-hidden='true'></span> More Info
          <% end %>
        </p>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'days_destroyed.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='days_destroyed_daily'>
          <%= link_to 'Days Destroyed Daily', charts_days_destroyed_path %>
        </h3>
      </div>
    </section>
    
    <section class="row m-b-md">
      <div class="col-sm-4 chart_img">
        <%= image_tag asset_path 'blockchain_size.png' %>
      </div>
      <div class="col-sm-8 chart_link">
        <h3 id='blockchain_size'>
          <%= link_to 'Blockchain Size', charts_blockchain_size_path %>
        </h3>
        <p>Total size of all block headers and transactions.</p>
      </div>
    </section>
  </section>
</div>