config/routes.rb
Rails.application.routes.draw do
  root 'explorers#index'
  get '/.well-known/acme-challenge/:id' => 'explorers#letsencrypt'
  mount Resque::Server, at: '/resque'
  devise_for :users, path_names: {
    verify_authy: "/verify-token",
    enable_authy: "/enable-two-factor",
    verify_authy_installation: "/verify-installation"
  }
  resources :users, except: [:index] do
    get 'confirm_node_created' => 'chains#confirm_node_created', path: 'chains/confirm_node_created'
    resources :chains do
      get 'start'
      get 'stop'
      
      get 'get_best_block_hash'
      get 'get_block'
      get 'get_blockchain_info'
      get 'get_block_count'
      get 'get_block_hash'
      get 'get_block_header'
      get 'get_chain_tips'
      get 'get_difficulty'
      get 'get_info'
      get 'get_mem_pool_info'
      get 'get_raw_mem_pool'
      get 'get_tx_out'
      get 'get_tx_out_proof'
      get 'get_tx_outset_info'
      get 'verify_chain'
      get 'verify_tx_out_proof'
      
      get 'generate'
      get 'get_generate'
      get 'set_generate'
      
      get 'get_block_template'
      get 'get_mining_info'
      get 'get_network_hashps'
      get 'prioritise_transaction'
      get 'submit_block'
      
      get 'add_node'
      get 'disconnect_node'
      get 'get_added_node_info'
      get 'get_connection_count'
      get 'get_net_totals'
      get 'get_network_info'
      get 'get_peer_info'
      get 'list_banned'
      get 'clear_banned'
      get 'ping'
      get 'set_ban'
      
      get 'create_raw_transaction'
      get 'decode_raw_transaction'
      get 'decode_script'
      get 'get_raw_transaction'
      get 'send_raw_transaction'
      get 'sign_raw_transaction'

      get 'create_multi_sig'
      get 'estimate_fee'
      get 'estimate_priority'
      get 'estimate_smart_fee'
      get 'estimate_smart_priority'
      get 'validate_address'
      get 'verify_message'
    end
  end
  get 'apps/bookmarks' => 'apps#bookmarks'
  get 'apps/calculator' => 'apps#calculator'
  get 'charts/show' => 'charts#show', path: 'charts'
  get 'charts/circulation' => 'charts#circulation'
  get 'charts/market_cap' => 'charts#market_cap'
  get 'charts/transaction_fees_btc' => 'charts#transaction_fees_btc'
  get 'charts/transaction_fees_usd' => 'charts#transaction_fees_usd'
  get 'charts/network_deficit' => 'charts#network_deficit'
  get 'charts/transactions_daily' => 'charts#transactions_daily'
  get 'charts/transactions_total' => 'charts#transactions_total'
  get 'charts/unique_addresses' => 'charts#unique_addresses'
  get 'charts/average_transactions' => 'charts#average_transactions'
  get 'charts/orphaned_blocks' => 'charts#orphaned_blocks'
  get 'charts/total_output_volume' => 'charts#total_output_volume'
  get 'charts/market_price' => 'charts#market_price'
  get 'charts/hash_rate' => 'charts#hash_rate'
  get 'charts/difficulty' => 'charts#difficulty'
  get 'charts/days_destroyed_cumulative' => 'charts#days_destroyed_cumulative'
  get 'charts/days_destroyed' => 'charts#days_destroyed'
  get 'charts/blockchain_size' => 'charts#blockchain_size'
  resources :explorers, only: [:index], path: 'coin'
  get 'explorers/search', path: 'search'
  get 'explorers/cloud', path: 'cloud'
  resources :blocks, only: [:show]
  get 'blocks/transactions/:id' => 'blocks#transactions'
  get 'blocks/raw/:id' => 'blocks#raw'
  resources :transactions, only: [:show]
  get 'transactions/raw/:id' => 'transactions#raw'
  resources :addresses, only: [:show]
  get 'addresses/balance/:id' => 'addresses#balance'
  get 'addresses/unspent/:id' => 'addresses#unspent'
  
  get 'docs/docs'
  get 'docs/developers'
  get 'docs/api'
  get 'docs/security'
  get 'docs/credit'

end

app/models/chain.rb
class Chain < ActiveRecord::Base
  belongs_to :user
end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
  before_action :set_chain, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  include BigEarth::Blockchain::Utility

  # GET /users/1/chains
  # GET /users/1/chains.json
  def index
    @chains = Chain.all
  end

  # GET /users/1/chains/1
  # GET /users/1/chains/1.json
  def show
    # Namespace the title by the user's email so that no global titles conflict
  end

  # GET /users/1/chains/new
  def new
    @user = User.find params[:user_id]
    @chain = @user.chains.new
  end

  # GET /users/1/chains/edit
  def edit
  end

  # POST /users/1chains
  # POST /users/1chains.json
  def create
    @user = User.find params[:user_id]
    @chain = @user.chains.new chain_params

    respond_to do |format|
      if @chain.save 
        # Send an email to the user
        BigEarth::Blockchain::ChainCreatedEmailJob.perform_later @user, @chain
        
        # format data 
        # config = {
        #   type: 'blockchain',
        #   title: @chain.title,
        #   email: @user.email,
        #   options: {
        #     flavor: @chain.flavor
        #   }
        # }
        # Create node
        # BigEarth::Blockchain::CreateNodeJob.perform_later config
        
        # Mask IP address behind DNS A record
        # Resque.enqueue_in 15.seconds, BigEarth::Blockchain::CreateDNSRecord, config
        
        format.html { redirect_to [@user, @chain] }
        format.json { render :show, status: :created, location: @chain }
      else
        format.html { render :new }
        format.json { render json: @chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1/chains/1
  # PATCH/PUT /users/1/chains/1.json
  def update
    respond_to do |format|
      if @chain.update(chain_params)
        format.html { redirect_to @chain, notice: 'Chain was successfully updated.' }
        format.json { render :show, status: :ok, location: @chain }
      else
        format.html { render :edit }
        format.json { render json: @chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1/chains/1
  # DELETE /users/1/chains/1.json
  def destroy
    
    # Wrap in begin/rescue block
    begin
      title = @chain.title
      
      # Format config hash
      # config = {
      #   type: 'blockchain',
      #   title: title,
      #   email: @user.email
      # }
      
      # Queue up BigEarth::Blockchain::DestroyNodeJob
      # BigEarth::Blockchain::DestroyNodeJob.perform_later config
      
      # Destroy the DNS A record
      # BigEarth::Blockchain::DestroyDNSRecordJob.perform_later config
        
      # Send an email to the user
      BigEarth::Blockchain::ChainDestroyedEmailJob.perform_later @user, title
      
      # Delete the chain from DB
      @chain.destroy
    rescue => error
      puts "[ERROR] #{Time.now}: #{error.class}: #{error.message}"
    end
    respond_to do |format|
      format.html { redirect_to @user, notice: "Chain '#{title}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /users/1/chains/confirm_node_created
  def confirm_node_created
    
    user = User.find params[:user_id]
    chain = user.chains.where('title = ?', params[:title]).first
    if chain.node_created
      # Namespace the title by the user's email so that no global titles conflict
      formatted_title = format_title params[:title], user.email
      
      @response = {
        status: 200,
        message: 'node created',
        url: "#{formatted_title}.bigearth.io"
      }
    else
      @response = {
        status: 200,
        message: 'node not created'
      }
    end
    respond_to do |format|
      format.json { render json: @response }
    end
  end
  
  # blockchain
  
  def get_best_block_hash
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_best_block_hash.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_block
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_block.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      query: params['data'],
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_blockchain_info
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_blockchain_info.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_block_count
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_block_count.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_block_hash
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_block_hash.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      query: params['data'],
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_block_header
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_block_header.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      query: params['data'],
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_chain_tips
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_chain_tips.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_difficulty
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_difficulty.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_mem_pool_info
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_mem_pool_info.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_raw_mem_pool
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_raw_mem_pool.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_tx_out
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_tx_out.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_tx_out_proof
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_tx_out_proof.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def get_tx_outset_info
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/get_tx_outset_info.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|
      format.json { render json: JSON.parse(@response) }
    end
  end
  
  def verify_chain
    require 'httparty'
    @response = HTTParty.get("https://#{Figaro.env.blockchain_url}/verify_chain.json", 
      basic_auth: {
        username: Figaro.env.blockchain_proxy_username, 
        password: Figaro.env.blockchain_proxy_password
      },
      headers: { 'Content-Type' => 'application/json' } 
    )
    respond_to do |format|

app/helpers/chains_helper.rb
module ChainsHelper
end

app/views/chains/_blockchain.html.erb
<div class='parent_folder' data-child_folder='blockchain'>
  <section class='row'>
    <div class='col-md-3 text-center folder_icon'>
      <span class='glyphicon glyphicon-folder-close' aria-hidden='true'></span>
    </div>
    <div class='col-md-9'>
      <h4>Blockchain</h4>
      <p>15 Requests</p>
    </div>
  </section>
</div>

<ul id='blockchain' class='hide requests'>
  <li>
    <%= link_to user_chain_get_best_block_hash_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getbestblockhash'>getbestblockhash</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_block_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getblock'>getblock</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_blockchain_info_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getblockchaininfo'>getblockchaininfo</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_block_count_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getblockcount'>getblockcount</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_block_hash_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getblockhash'>getblockhash</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_block_header_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getblockheader'>getblockheader</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_chain_tips_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getchaintips'>getchaintips</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_difficulty_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getdifficulty'>getdifficulty</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_mem_pool_info_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getmempoolinfo'>getmempoolinfo</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_raw_mem_pool_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getrawmempool'>getrawmempool</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_tx_out_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='gettxout'>gettxout</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_tx_out_proof_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='gettxoutproof'>gettxoutproof</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_tx_outset_info_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='gettxoutsetinfo'>gettxoutsetinfo</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_verify_chain_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='verifychain'>verifychain</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_verify_tx_out_proof_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='verifytxoutproof'>verifytxoutproof</code>
      </div>
    </section>
    <% end %>
  </li>
</ul>

app/views/chains/_control.html.erb
<div class='parent_folder' data-child_folder='control'>
  <section class='row'>
    <div class='col-md-3 text-center folder_icon'>
      <span class='glyphicon glyphicon-folder-close' aria-hidden='true'></span>
    </div>
    <div class='col-md-9'>
      <h4>Control</h4>
      <p>4 Requests</p>
    </div>
  </section>
</div>

<ul id='control' class='hide requests'>
  <li>
    <%= link_to user_chain_start_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb post'>
        POST
      </div>
      <div class='col-md-9'>
        <code data-action='start'>start</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_stop_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb post'>
        POST
      </div>
      <div class='col-md-9'>
        <code data-action='stop'>stop</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_info_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getinfo'>getinfo</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to [@user, @chain], method: :delete, data: { confirm: "Permanently delete Chain '#{@chain.title}'? This action is undoable." } do %>
      <section class='row'>
        <div class='col-md-3 text-center http_verb delete'>
          DELETE
        </div>
        <div class='col-md-9'>
          <code data-action='destroy'>destroy</code>
        </div>
      </section>
    <% end %>
  </li>
</ul>

app/views/chains/_network.html.erb
<div class='parent_folder' data-child_folder='network'>
  <section class='row'>
    <div class='col-md-3 text-center folder_icon'>
      <span class='glyphicon glyphicon-folder-close' aria-hidden='true'></span>
    </div>
    <div class='col-md-9'>
      <h4>Network</h4>
      <p>11 Requests</p>
    </div>
  </section>
</div>

<ul id='network' class='hide requests'>
  <li>
    <%= link_to user_chain_add_node_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb post'>
        POST
      </div>
      <div class='col-md-9'>
        <code data-action='addnode'>addnode</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_clear_banned_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb post'>
        POST
      </div>
      <div class='col-md-9'>
        <code data-action='clearbanned'>clearbanned</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_disconnect_node_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb post'>
        POST
      </div>
      <div class='col-md-9'>
        <code data-action='disconnectnode'>disconnectnode</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_added_node_info_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getaddednodeinfo'>getaddednodeinfo</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_connection_count_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getconnectioncount'>getconnectioncount</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_net_totals_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getnettotals'>getnettotals</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_network_info_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getnetworkinfo'>getnetworkinfo</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_get_peer_info_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='getpeerinfo'>getpeerinfo</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_list_banned_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='listbanned'>listbanned</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_ping_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='ping'>ping</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_set_ban_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb post'>
        POST
      </div>
      <div class='col-md-9'>
        <code data-action='setban'>setban</code>
      </div>
    </section>
    <% end %>
  </li>
</ul>

app/views/chains/_util.html.erb
<div class='parent_folder' data-child_folder='util'>
  <section class='row'>
    <div class='col-md-3 text-center folder_icon'>
      <span class='glyphicon glyphicon-folder-close' aria-hidden='true'></span>
    </div>
    <div class='col-md-9'>
      <h4>Util</h4>
      <p>7 Requests</p>
    </div>
  </section>
</div>

<ul id='util' class='hide requests'>
  <li>
    <%= link_to user_chain_create_multi_sig_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb post'>
        POST
      </div>
      <div class='col-md-9'>
        <code data-action='createmultisig'>createmultisig</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_estimate_fee_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='estimatefee'>estimatefee</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_estimate_priority_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='estimatepriority'>estimatepriority</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_estimate_smart_fee_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='estimatesmartfee'>estimatesmartfee</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_estimate_smart_priority_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='estimatesmartpriority'>estimatesmartpriority</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_validate_address_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='validateaddress'>validateaddress</code>
      </div>
    </section>
    <% end %>
  </li>
  <li>
    <%= link_to user_chain_verify_message_path(@user, @chain) do %>
    <section class='row'>
      <div class='col-md-3 text-center http_verb get'>
        GET
      </div>
      <div class='col-md-9'>
        <code data-action='verifymessage'>verifymessage</code>
      </div>
    </section>
    <% end %>
  </li>
</ul>